-- Knotes baseline schema for a new Supabase project.
-- Apply this first, then the dated hardening migrations in order.
begin;

create extension if not exists pgcrypto with schema extensions;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  username text not null unique,
  avatar_url text,
  about text,
  is_admin boolean not null default false,
  is_public boolean not null default false,
  theme_preference text not null default 'system',
  created_at timestamptz not null default now()
);

create table if not exists public.blogs (
  id bigint generated by default as identity primary key,
  title text not null,
  url text not null default '',
  content text not null default '',
  category text not null default 'Other',
  author text,
  author_id uuid references auth.users(id) on delete set null,
  slug text unique,
  status text not null default 'published',
  published_at timestamptz not null default now(),
  updated_at timestamptz,
  likes_count bigint not null default 0,
  comments_count bigint not null default 0,
  clicks_count bigint not null default 0
);

create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  blog_id bigint not null references public.blogs(id) on delete cascade,
  user_id uuid references auth.users(id) on delete set null,
  user_name text,
  comment_text text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.likes (
  id bigint generated by default as identity primary key,
  blog_id bigint not null references public.blogs(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (blog_id, user_id)
);

create table if not exists public.bookmarks (
  id bigint generated by default as identity primary key,
  blog_id bigint not null references public.blogs(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (blog_id, user_id)
);

create table if not exists public.hidden_stories (
  user_id uuid not null references auth.users(id) on delete cascade,
  blog_id bigint not null references public.blogs(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, blog_id)
);

create table if not exists public.search_stats (
  id bigint generated by default as identity primary key,
  term text not null unique,
  count bigint not null default 1,
  created_at timestamptz not null default now(),
  last_searched_at timestamptz not null default now()
);

create table if not exists public.site_settings (
  id text primary key,
  value jsonb not null,
  updated_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.blogs enable row level security;
alter table public.comments enable row level security;
alter table public.likes enable row level security;
alter table public.bookmarks enable row level security;
alter table public.hidden_stories enable row level security;
alter table public.search_stats enable row level security;
alter table public.site_settings enable row level security;

grant select, insert, update, delete on public.profiles, public.blogs, public.comments,
  public.likes, public.bookmarks, public.hidden_stories, public.search_stats,
  public.site_settings to authenticated;
grant usage, select on all sequences in schema public to authenticated;

-- Later private-circle policies make this callable only through RLS.
create or replace function public.search_all_content(
  search_query text,
  page_limit integer default 100,
  page_offset integer default 0
)
returns table (
  id bigint, title text, url text, content text, category text, author text,
  author_id uuid, slug text, status text, published_at timestamptz,
  likes_count bigint, comments_count bigint, clicks_count bigint, total_count bigint
)
language sql
stable
security invoker
set search_path = ''
as $$
  select b.id, b.title, b.url, b.content, b.category, b.author, b.author_id,
    b.slug, b.status, b.published_at, b.likes_count, b.comments_count,
    b.clicks_count, count(*) over ()
  from public.blogs b
  where b.title ilike '%' || search_query || '%'
     or b.content ilike '%' || search_query || '%'
  order by b.published_at desc
  limit greatest(1, least(page_limit, 100))
  offset greatest(page_offset, 0);
$$;

revoke all on function public.search_all_content(text, integer, integer) from public, anon;
grant execute on function public.search_all_content(text, integer, integer) to authenticated;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values
  ('avatars', 'avatars', false, 2097152, array['image/jpeg', 'image/png', 'image/webp', 'image/gif']),
  ('media', 'media', false, 10485760, array['image/jpeg', 'image/png', 'image/webp', 'image/gif'])
on conflict (id) do nothing;

commit;
